apiVersion: v1
kind: Service
metadata:
  name: sample-website-service
spec:
  type: LoadBalancer
  selector:
    app: sample-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
